// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAek-sovI5tt2hskn1m1zKidWSyW59RUos',
    appId: '1:608056487424:web:22200b892fbec1cd66b2e5',
    messagingSenderId: '608056487424',
    projectId: 'etradeling-test',
    authDomain: 'etradeling-test.firebaseapp.com',
    storageBucket: 'etradeling-test.appspot.com',
    measurementId: 'G-EM2FQRXSC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfoeLXDoy9TwcFzrZgwQCAEvtAKBbszjo',
    appId: '1:608056487424:android:243e0578dde9eeed66b2e5',
    messagingSenderId: '608056487424',
    projectId: 'etradeling-test',
    storageBucket: 'etradeling-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-xQstvca_1z1SLI3sGEzDtkQUZPJC7cQ',
    appId: '1:608056487424:ios:9d96ec6224cd8d2666b2e5',
    messagingSenderId: '608056487424',
    projectId: 'etradeling-test',
    storageBucket: 'etradeling-test.appspot.com',
    iosBundleId: 'com.example.etradeling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-xQstvca_1z1SLI3sGEzDtkQUZPJC7cQ',
    appId: '1:608056487424:ios:8812f1376ffbdac666b2e5',
    messagingSenderId: '608056487424',
    projectId: 'etradeling-test',
    storageBucket: 'etradeling-test.appspot.com',
    iosBundleId: 'com.example.etradeling.RunnerTests',
  );
}
